using SPTarkov.Common.Models.Logging;
using SPTarkov.DI.Annotations;
using SPTarkov.Server.Core.DI;
using SPTarkov.Server.Core.Helpers.Server;
using SPTarkov.Server.Core.Models.Spt.Mod;
using System.Reflection;

using DRIP.Services;

namespace DRIP
{
    // 4.1: mod metadata is the IModMetadata interface, not an abstract record. The interface
    // wants get;set; on everything, so init-only defaults are gone; values are set in the
    // constructor instead. IsBundleMod is no longer on the interface - kept as a plain
    // property because 4.1's BundleLoader serves whatever a mod registers regardless.
    public class ModMetadata : IModMetadata
    {
        public string Name { get; init; } = "DRIP Core";
        public string Author { get; init; } = "MILF Modding Team";
        public List<string>? Contributors { get; init; } =
        [
            "Sophia",
            "Colette Blackpaw",
            "Amber",
            "JustNU",
            "RaiRaiTheRaichu",
            "Virtual"
            // TODO: anyone I missed?
        ];
        public SemanticVersioning.Version Version { get; init; } = new("2.1.0");
        public SemanticVersioning.Range SptVersion { get; init; } = new("~4.1.0");


        public List<string>? Incompatibilities { get; init; }

        public Dictionary<string, SemanticVersioning.Range>? ModDependencies { get; init; } = new();
        public string? Url { get; init; }
        public bool HasPrepatcher { get; init; }
        public string License { get; init; } = "MIT";
        public string ModGuid { get; init; } = "gov.milfmodding.drip.core";
        public bool IsBundleMod = true;
    }

    // LOAD ORDER IS LOAD-BEARING. Do not move this later without reading the whole comment.
    //
    // DRIP writes item, clothing and customization templates into the database, and three core stages *consume* the
    // database after PostDBModLoader. Every one of them runs before PostSptModLoader, which is where this used to sit:
    //
    //   SaveCallbacks      700,000  SaveServer.LoadAsync -> ProfileValidatorService.MigrateAndValidateProfile
    //                               -> ProfileValidatorHelper.CheckForOrphanedModdedData
    //   TraderCallbacks    800,000  TraderController.Load - sets NextResupply, applies TraderPriceMultiplier
    //   RagfairCallbacks 1,000,000  RagfairPriceService.Load - RefreshStaticPrices / ReplaceFleaBasePrices
    //
    // The first is a release blocker and the reason this moved. CheckForOrphanedModdedData runs SIX validators, each
    // asking the database whether a template the profile references still exists - items, user builds, dialog records
    // (mail rewards), clothing, repeatable quests, trader purchases. At PostSptModLoader none of DRIP's templates
    // existed yet, so a profile that owned any DRIP content was found to reference templates "that do not exist in
    // SPT" and was marked invalid on the next start. Sophia hit the clothing validator first because she bought three
    // T-shirts; owning a DRIP item, or having unread mail containing one, reaches the others.
    //
    // Worse, SPT's advice for that error is to set removeModItemsFromProfile, which makes those validators *delete*
    // the offending data instead of throwing - so the documented remedy destroys the player's DRIP gear. And
    // RemoveInvalidUserBuilds filters unconditionally with no config gate and no exception at all, so weapon and
    // equipment builds containing DRIP items are dropped silently either way.
    //
    // The other two were latent bugs the move also fixes: DRIP's own traders were created after the loop that gives
    // traders a resupply timestamp, and DRIP's items were added after static flea prices were generated.
    //
    // Anything in (PostDBModLoader, SaveCallbacks) is correct. PostDBModLoader + 2 is chosen because it is what the
    // stage is for - "the database is loaded, now let mods change it" - and because being earliest leaves the most
    // room. Everything DRIP *reads* comes from DatabaseImporter (200,000) or from configs, so nothing is missed.
    //
    // Known, accepted cost, and it is bigger than "modded traders": DRIPTraderAssortService indexes every trader's
    // assort to honour copyOriginalOffers, and at 400,002 two kinds of trader stock do not exist yet.
    //
    //   * traders another mod registers at TraderRegistration (500,000) or later - expected, minor;
    //   * FENCE, which is vanilla. Fence's assort is not loaded, it is GENERATED by
    //     FenceBaseAssortGenerator.GenerateFenceBaseAssorts during TraderCallbacks (800,000), from a walk over the
    //     whole item database. At 400,002 its assort is empty, so the index finds nothing for it.
    //
    // Do not write "all vanilla traders load at 200,000" here. That was believed on 2026-07-29, it is false, and it
    // is the reason ~102 offers and 20 sellers went missing when this priority moved - each copy-mode item had been
    // getting one offer from Fence, because Fence's generated stock is very nearly the entire item list. For 85 items
    // that offer was a duplicate of a real trader's; for 20 it was the only one. See DRIPTraderAssortService.BuildIndex,
    // whose log line measures exactly this, and CONTENT-ISSUES in docs/STATUS.md for the 13-vs-7 split of those 20.
    //
    // Fixing this properly needs a split - templates registered early, the assort pass late - because the profile
    // constraint (before 700,000) and the Fence constraint (after 800,000) cannot both be met by one slot. That is a
    // real change and not worth making blind; profiles surviving a restart beat Fence duplicates.
    // (4.1 note: the old "+2 after WTT-ServerCommonLib" offset is retired - WTT's tooling was an abandoned
    // pre-4.1 experiment and the slot is now measured against vanilla priorities directly. See
    // docs/SPT-4.1-MIGRATION.md.)
    //
    // Mods at a HIGHER priority than us are the live version of the cost above, not a hypothetical: on the 4.0.11
    // install EcoAttachmentEmporium loads at PostDBModLoader + 20, i.e. after us. Anything it adds to a trader's
    // assort is invisible to DRIPTraderAssortService. Harmless while the two mods touch different item classes
    // (attachments vs clothing and armour), and the first thing to suspect if a DRIP retexture of an item some other
    // mod sells stops appearing.
    // THE 4.1 SLOT IS Routers + 50_000 (= 450,000), derived in docs/SPT-4.1-MIGRATION.md:
    // 4.1 removed both mod-loader enum slots, so the slot is now measured against vanilla
    // priorities directly. DRIP needs: after DB hydration, before SaveCallbacks (600,000,
    // profile validation - the original bug this fixed) and before HandbookCallbacks
    // (500,000), TraderCallbacks (700,000, resupply stamps) and RagfairCallbacks (900,000,
    // flea static prices). 450,000 satisfies all with room either side.
    [Injectable(TypePriority = OnLoadOrder.Routers + 50_000)]
    public class DRIP(
        ISptLogger<DRIP> logger,
        ModHelper modHelper,
        DRIPCustomItemService dripCustomItemService,
        DRIPCustomClothingService dripCustomClothingService,
        DRIPCustomTraderService dripCustomTraderService,
        DRIPTraderAssortService dripTraderAssortService,
        DRIPItemPresetService dripItemPresetService,
        DRIPCustomQuestService dripCustomQuestService,
        DRIPCustomLocaleService dripCustomLocaleService,
        DripConfigService dripConfigService,
        DRIPVerificationService dripVerificationService) : IOnLoad
    {
        public async Task OnLoadAsync(CancellationToken cancellationToken)
        {
            var assembly = Assembly.GetExecutingAssembly();

            // Fundamentally, DRIP is a series of Content Packs that assembles itself at runtime, allowing people to
            // determine what items they want in their playthroughs.
            //
            // This also helps immensely with testing and building new items, since DRIP does not need to be re-compiled
            // or adjusted just to add a single new item.
            var assemblyLocation = modHelper.GetAbsolutePathToModFolder(assembly);
            var contentPacksPath = Path.Combine(assemblyLocation, "bundles", "ContentPacks");

            // TODO: error handling?
            foreach (var fullPackPath in Directory.EnumerateDirectories(contentPacksPath))
            {
                var packName = new DirectoryInfo(fullPackPath).Name;
                var packDirectory = Path.GetRelativePath(assemblyLocation, fullPackPath).Replace("\\", "/");
                logger.Info($"[DRIP] Loading Content Pack \"{packName}\"");

                // DRIP-Specific Loaders ///////////////////////////////////////////////////////////////////////////////
                // We need to load the traders first because all our custom items depend on them. :)
                await DoIfPathExists(fullPackPath, "CustomTraders", async () =>
                {
                    await dripCustomTraderService.CreateCustomTraders(assembly, $"{packDirectory}/CustomTraders");
                });

                // Locales before quests: quest fields are locale keys, so the text has to be in place for the names
                // players see to resolve.
                //
                // Both of these come before the bundle check below, deliberately. Neither needs a single bundle, so
                // an un-bootstrapped checkout should still get working quests and text rather than nothing at all.
                await DoIfPathExists(fullPackPath, "CustomLocales", async () =>
                {
                    await dripCustomLocaleService.CreateCustomLocales(assembly, $"{packDirectory}/CustomLocales");
                });

                await DoIfPathExists(fullPackPath, "CustomQuests", async () =>
                {
                    await dripCustomQuestService.CreateCustomQuests(assembly, $"{packDirectory}/CustomQuests");
                });

                // A pack with no bundles anywhere is an un-bootstrapped checkout, not a broken pack: the repository
                // ships configs only and players get bundles in the release archive. Saying so once beats emitting
                // an identical error for all 275 items - and it keeps a genuinely missing bundle, reported per item
                // below, distinguishable from this.
                if (!HasAnyBundles(fullPackPath))
                {
                    logger.Warning(
                        $"[DRIP] Content Pack \"{packName}\" has no bundles, so none of its items or clothing can " +
                        "load. This is the expected state of a fresh checkout - bundles are not kept in git. " +
                        "Populate them with:  python tools/convert-legacy.py --part 1 " +
                        $"--out \"bundles/ContentPacks/{packName}\" --bundles link");
                    continue;
                }

                await DoIfPathExists(fullPackPath, "CustomItems", async () =>
                {
                    await dripCustomItemService.CreateCustomItems(assembly, $"{packDirectory}/CustomItems");
                });

                await DoIfPathExists(fullPackPath, "CustomClothing", async () =>
                {
                    await dripCustomClothingService.CreateCustomClothing(assembly, $"{packDirectory}/CustomClothing");
                });

                // Content kinds DRIP does not load, inherited from the WTT template it was scaffolded from:
                // achievements, assort schemes, bot loadouts, hideout recipes. No content pack uses any of them.
                //
                // This was six lines of commented-out `await wttCommon.*` calls. Deleted rather than kept, because
                // two of the six - locales and quests - are implemented above, so the block claimed as missing two
                // features that exist. Commented-out code that no longer compiles against a dependency we vendored
                // decays exactly like any other stale comment and cannot be caught by a build.
            }

            // Cross-Pack Fixups ///////////////////////////////////////////////////////////////////////////////////
            // Deferred until every pack has loaded, so this is one pass over the item database rather than one per
            // content pack. It also means a later pack's items inherit compatibility just as an earlier pack's do.
            dripCustomItemService.ApplyInheritedSlotFiltersAndConflicts();
            dripCustomItemService.ApplyBotWeightings();
            dripCustomClothingService.ApplyBotAppearance();

            // Quests last: they reference items by name, so every pack's items must exist first.
            dripCustomQuestService.ApplyAll();

            // Needs an index over every trader's assort, so it is built once here rather than per item.
            dripTraderAssortService.ApplyAll();

            // Gives each item a default preset so the flea sells it with its plates fitted. Deferred to here for the
            // same reason as the rest: one pass over every pack's items, and it must see them all.
            await dripItemPresetService.ApplyAll();

            // Global options that transform the vanilla database rather than gate a loader.
            dripConfigService.ApplyVanillaClothingPrices(assembly);

            // Self-check ///////////////////////////////////////////////////////////////////////////////////////////
            // Asserts the database we just built is coherent. Every check corresponds to a bug that reached us once.
            dripVerificationService.VerifyAll();

            // Clothing Tags Integration ///////////////////////////////////////////////////////////////////////////////
            // TODO: integrate with ICUP :)
        }

        /// <summary>
        /// Whether a content pack has any bundles at all, anywhere beneath it.
        /// </summary>
        private static bool HasAnyBundles(string packPath)
        {
            return Directory.EnumerateFiles(packPath, "*.bundle", SearchOption.AllDirectories).Any();
        }

        /// <summary>
        /// Conditionally apply a function if the given directory exists. We mostly do this to avoid a ton of confusing
        /// logging if a content pack doesn't have a given thing like CustomBotLoadouts or whatever.
        /// </summary>
        private static async Task DoIfPathExists(string basePath, string search, Func<Task> toDo)
        {
            var fullPath = Path.Combine(basePath, search);
            if (Directory.Exists(fullPath))
            {
                await toDo();
            }
        }
    }
}
